# Image into numpy array

In [29]:
from matplotlib.image import imread
import numpy as np

In [30]:
nmpy = imread('numpy.png')

In [31]:
nmpy.size

2280000

In [32]:
nmpy.shape
# total rows, wideness, total nmbr of channels used in image

(475, 1200, 4)

In [33]:
nmpy[:,:,0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [34]:
nmpy[200,200,:]

array([0.40784314, 0.5411765 , 0.7607843 , 0.99607843], dtype=float32)

# Convert it into Gray Scale Image
##                   Gray = R + G+ B / 3
###        Gray = ((0.3*R) + (0.59*G) + (0.11 * B))

In [35]:
catImg = imread('cat.jpg')

In [36]:
catImg.shape

(390, 640, 3)

In [37]:
catImg[0][0]
# RGB

array([28, 38,  0], dtype=uint8)

In [38]:
(28 + 38 + 0)/3

22.0

In [39]:
catImg[0][1]

array([69, 78, 31], dtype=uint8)

In [40]:
(69 + 78 + 31)/3

59.333333333333336

In [41]:
np.dot(catImg[0][0], [0.34,0.33,0.33])
np.dot(catImg[0][1], [0.34,0.33,0.33])

59.43000000000001

In [42]:
np.dot(catImg[:,:,: 3], [0.34, 0.33, 0.33])

array([[ 22.06,  59.43,  26.42, ..., 124.32, 125.32, 125.32],
       [  6.34,  17.71,  31.04, ..., 125.32, 126.32, 126.32],
       [113.03,  50.03,  32.03, ..., 126.66, 127.66, 128.66],
       ...,
       [ 21.99,  43.39,  59.07, ...,  62.9 ,  62.9 ,  63.9 ],
       [ 22.66,  32.39,  57.07, ...,  60.9 ,  61.9 ,  62.9 ],
       [ 23.33,  29.04,  62.07, ...,  58.9 ,  59.9 ,  60.9 ]])

In [43]:
# catImg[:,:,: 3]

In [45]:
grayscale_image = np.dot(catImg[:,:,: 3], [0.3, 0.59, 0.11])

In [46]:
grayscale_image.shape

(390, 640)

In [47]:
import matplotlib.pyplot as plt

In [48]:
plt.imsave('gray.jpg', grayscale_image, cmap=plt.get_cmap("gray"))

In [50]:
invert_image = 255 - grayscale_image
plt.imsave('invert.jpg', invert_image, cmap=plt.get_cmap("gray"))

In [51]:
np.max(grayscale_image)
np.min(grayscale_image)

0.0

In [53]:
binary = grayscale_image > 127
plt.imsave('binary.jpg', binary, cmap=plt.get_cmap("gray"))

# Image Filters

In [54]:
avg_filter = 0.11 * np.ones((3,3))

In [55]:
avg_filter

array([[0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11]])

In [57]:
grayscale_image.shape

(390, 640)

In [58]:
filter_image = np.empty((grayscale_image.shape[0] - 2, grayscale_image.shape[1] - 2))

In [59]:
filter_image.shape

(388, 638)

In [61]:
for i in range(filter_image.shape[0]):
    for j in range(filter_image.shape[1]):
        subpart = grayscale_image[i : i+3, j : j+3]
        pixel = np.sum(np.multiply(subpart, avg_filter))
        filter_image[i, j] = pixel

In [62]:
filter_image

array([[ 45.3673,  38.1755,  32.5864, ..., 146.9358, 148.06  , 148.8542],
       [ 87.9065,  64.9055,  43.5226, ..., 148.9312, 150.0554, 151.0696],
       [126.8927, 114.1371,  90.013 , ..., 151.3908, 152.7229, 153.945 ],
       ...,
       [ 55.9383,  67.8568,  68.2594, ...,  80.6817,  81.4286,  82.4186],
       [ 53.5898,  69.3968,  75.4094, ...,  79.5817,  80.4386,  81.4286],
       [ 50.9245,  65.3873,  76.7294, ...,  78.2617,  79.1186,  80.1086]])

In [63]:
plt.imsave('avg_filter.jpg', filter_image, cmap=plt.get_cmap("gray"))

In [64]:
def apply_filter(srcImg, kernel):
    filter_image = np.empty((srcImg.shape[0] - 2, srcImg.shape[1] - 2))

    for i in range(filter_image.shape[0]):
        for j in range(filter_image.shape[1]):
            subpart = grayscale_image[i : i+3, j : j+3]
            pixel = np.sum(np.multiply(subpart, kernel))
            filter_image[i, j] = pixel
    return filter_image

In [67]:
edge_filter = np.array([[-1,0,-1], [-2,0,2], [-1,0,1]])

In [70]:
edge_images = apply_filter(grayscale_image, edge_filter)

In [72]:
plt.imsave('edge_filter.jpg', edge_images, cmap=plt.get_cmap("gray"))