# Binary Operations

In [2]:
import numpy as np

In [4]:
np.binary_repr(4)
np.binary_repr(4, 40)

'0000000000000000000000000000000000000100'

In [6]:
np.bitwise_and(5,6)

4

In [7]:
np.bitwise_or(3,4)

7

In [8]:
np.invert(10)

-11

In [10]:
np.left_shift(8,4)
# 8*2*2*2*2

128

In [11]:
np.right_shift(30,2)

7

# Mathematical Function

In [12]:
np.pi

3.141592653589793

In [14]:
np.degrees(np.pi)

180.0

In [15]:
np.deg2rad(180)

3.141592653589793

In [19]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [21]:
np.sin(a)
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [22]:
np.arcsin(a)

/Users/atul/opt/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


array([0.        , 1.57079633,        nan,        nan,        nan])

In [23]:
np.round(4.5)

4.0

In [24]:
np.ceil(4.5)

5.0

In [25]:
np.abs(-5)

5

In [26]:
np.floor(5)

5.0

# Arithmetic Operations

In [27]:
a = np.array([1,2,3])
b = np.array([5,6,7])

In [28]:
a+b

array([ 6,  8, 10])

In [30]:
np.add(a,b)
np.subtract(a,b)

array([-4, -4, -4])

In [31]:
np.reciprocal([2,1,1])

array([0, 1, 1])

In [32]:
np.power([10,20],2)

array([100, 400])

In [33]:
np.power([10,20],[2,3])

array([ 100, 8000])

In [35]:
np.mod([10,20],7)
np.mod([10,20],[2,3])

array([0, 2])

# Statistical Function

In [36]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
np.amax(a)

15

In [39]:
np.amax(a, axis=0)
np.amax(a, axis=1)

array([ 3,  7, 11, 15])

In [41]:
np.amin(a)
np.amin(a, axis=0)

array([0, 1, 2, 3])

In [42]:
np.ptp(a)

15

In [43]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
np.mean(a)
np.mean(a, axis=0)
np.mean(a, axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

In [47]:
np.median(a)

7.5

In [49]:
np.percentile(a, 25)

3.75

In [50]:
np.std(a)

4.6097722286464435

In [51]:
np.var(a)

21.25

# Sorting & Searching

In [53]:
a = np.array([1,-4,2,6,7,0,-9])
a

array([ 1, -4,  2,  6,  7,  0, -9])

In [56]:
np.sort(a)

array([-9, -4,  0,  1,  2,  6,  7])

In [57]:
np.argsort(a)

array([6, 1, 5, 0, 2, 3, 4])

In [59]:
np.argmax(a)
np.argmin(a)

6

In [62]:
np.nonzero(a)

(array([0, 1, 2, 3, 4, 6]),)

In [63]:
np.where(a > 2)

(array([3, 4]),)

In [65]:
np.extract(a > 3, a)

array([6, 7])

# Copy & Views

In [66]:
a = np.array([2,3,4])

In [67]:
id(a)

4470840896

In [68]:
b = a

In [69]:
id(b)

4470840896

In [70]:
a[0] = -5

In [73]:
a , b

(array([-5,  3,  4]), array([-5,  3,  4]))

In [75]:
a = np.array([2,3,4])

In [76]:
id(a)

4470986032

In [77]:
b = a.view()

In [78]:
id(b)

4470988112

In [79]:
a[0] = 10

In [80]:
a, b

(array([10,  3,  4]), array([10,  3,  4]))

In [82]:
a = np.array([2,3,4])

In [83]:
id(a)

4471023536

In [84]:
b = a.copy()

In [85]:
id(b)

4471024496

In [86]:
a[0] = 20

In [87]:
a, b

(array([20,  3,  4]), array([2, 3, 4]))

# Linear Algebra Functions

In [88]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [90]:
np.linalg.matrix_rank(a)

2

In [91]:
np.trace(a)

15

In [92]:
np.linalg.det(a)

-9.51619735392994e-16

In [93]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [94]:
np.linalg.matrix_power(a, 3)

array([[ 468,  576,  684],
       [1062, 1305, 1548],
       [1656, 2034, 2412]])

In [96]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [97]:
np.linalg.svd(a)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

In [99]:
x + y = 5
2x - 5y = 10

SyntaxError: invalid syntax (<ipython-input-99-2e8ee7851350>, line 2)

In [100]:
a = np.array([[1,1], [2,-5]])
b = np.array([5,10])

In [102]:
np.linalg.solve(a,b)

array([5., 0.])

# I/O with Numpy

In [103]:
a = np.array([1,2,3,4])

In [104]:
np.save('out.bin', a)

In [105]:
np.load('out.bin.npy')

array([1, 2, 3, 4])

In [106]:
np.savetxt('data.txt', a)

In [107]:
np.loadtxt('data.txt')

array([1., 2., 3., 4.])