# Array Broadcasting

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([3,4,5])

In [4]:
a,b

(array([1, 2, 3]), array([3, 4, 5]))

In [5]:
a + b

array([4, 6, 8])

In [6]:
a = np.arange(12).reshape(4,3)
b = np.array([3,4,5])

In [7]:
a, b

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([3, 4, 5]))

In [8]:
a + b

array([[ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13],
       [12, 14, 16]])

In [9]:
a - b

array([[-3, -3, -3],
       [ 0,  0,  0],
       [ 3,  3,  3],
       [ 6,  6,  6]])

# Iterating over array

In [10]:
a = np.array([1,3,1,2])

In [11]:
for ele in np.nditer(a):
    print(ele)

1
3
1
2


In [12]:
b = np.arange(0,100,5).reshape(4,5)

In [15]:
for ele in np.nditer(b):
    print(ele+1)

1
6
11
16
21
26
31
36
41
46
51
56
61
66
71
76
81
86
91
96


# Array Manipulation 

In [20]:
a = np.arange(30)

In [22]:
b = a.reshape(5,6)

In [23]:
b.shape

(5, 6)

In [24]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
for ele in b.flat:
    print(ele)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [26]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [29]:
b.ravel()
b.ravel('C')
b.ravel('F')

array([ 0,  6, 12, 18, 24,  1,  7, 13, 19, 25,  2,  8, 14, 20, 26,  3,  9,
       15, 21, 27,  4, 10, 16, 22, 28,  5, 11, 17, 23, 29])

In [30]:
b.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [31]:
b.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [32]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [33]:
print(a), print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


(None, None)

In [34]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [36]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [39]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.split(a,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [41]:
b = np.arange(16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
np.hsplit(b,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [46]:
np.vsplit(b,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [47]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.append(a,22)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 22])

In [51]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
np.append(b,[100,200,300,400])
np.append(b,[[100,200,300,400]], axis=0)

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [100, 200, 300, 400]])

In [55]:
np.insert(a, 5, 100)

array([  0,   1,   2,   3,   4, 100,   5,   6,   7,   8,   9])

In [56]:
np.delete(a, 2)

array([0, 1, 3, 4, 5, 6, 7, 8, 9])